# Generated by Django 3.1.1 on 2020-10-08 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='mygig',
            name='c_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gig.category'),
        ),
        migrations.AddField(
            model_name='mygig',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
