# Generated by Django 3.1.1 on 2020-10-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0003_mygig_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygig',
            name='first_gig',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
