# Generated by Django 3.1.1 on 2020-10-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0004_mygig_first_gig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygig',
            name='first_gig',
        ),
    ]
