# Generated by Django 3.1.1 on 2020-10-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0006_auto_20201008_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygig',
            name='contact_no',
        ),
    ]
