# Generated by Django 3.1.1 on 2020-10-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0008_mygig_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygig',
            name='s_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gig.subcategory'),
        ),
    ]
