# Generated by Django 3.1.1 on 2020-10-12 05:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0009_auto_20201008_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygig',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
