# Generated by Django 3.1.1 on 2020-10-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0012_mygig_gig_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mygig',
            old_name='contact_no',
            new_name='profile',
        ),
    ]
