# Generated by Django 3.1.1 on 2020-10-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0013_auto_20201013_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygig',
            name='gig_image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gig_profile_thumbnail'),
        ),
    ]
