# Generated by Django 3.1.1 on 2020-10-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0014_mygig_gig_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygig',
            name='gig_image_thumbnail',
        ),
    ]
