# Generated by Django 3.1.1 on 2020-10-22 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gig', '0023_auto_20201021_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygig',
            name='likes',
        ),
        migrations.AddField(
            model_name='mygig',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('gigs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gig.mygig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
