# Generated by Django 3.1.1 on 2020-10-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0031_auto_20201030_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygig',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
