# Generated by Django 3.1.1 on 2020-10-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0032_auto_20201030_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10),
        ),
        migrations.AlterField(
            model_name='mygig',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
