# Generated by Django 3.1.1 on 2020-10-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0033_auto_20201030_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='value',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='Like', max_length=10),
        ),
        migrations.AlterField(
            model_name='mygig',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
