# Generated by Django 3.1.1 on 2020-11-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0043_auto_20201102_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='value',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='Like', max_length=10),
        ),
    ]
