# Generated by Django 3.1.1 on 2020-11-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0048_auto_20201124_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='s_name',
            field=models.CharField(max_length=1000),
        ),
    ]
