# Generated by Django 3.1.1 on 2020-11-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0049_auto_20201124_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_category/'),
        ),
    ]
