# Generated by Django 3.1.1 on 2020-10-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20200923_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='member_since',
        ),
    ]
