# Generated by Django 3.1.1 on 2020-10-01 12:09

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_remove_myprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='languages',
            field=models.ForeignKey(blank=True, default='English', null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.language'),
        ),
    ]
