# Generated by Django 3.1.1 on 2020-10-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20201001_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=30),
        ),
    ]
