# Generated by Django 3.1.1 on 2020-10-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_auto_20201002_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='profile_set',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
