# Generated by Django 3.1.1 on 2020-10-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_auto_20201003_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='img/default_profile_img.jpg', null=True, upload_to='user_profile_img'),
        ),
    ]
