# Generated by Django 3.1.1 on 2020-10-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_auto_20201003_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='description',
            field=models.CharField(blank=True, help_text='This is the grey text', max_length=300, null=True),
        ),
    ]
