# Generated by Django 3.1.1 on 2020-10-06 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0015_myprofile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='profile_set',
        ),
    ]
