# Generated by Django 3.1.1 on 2020-09-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='send_first_email',
            field=models.BooleanField(default=False),
        ),
    ]
