# Generated by Django 3.1.1 on 2020-10-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_account_joined_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_profile_set',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
