# Generated by Django 3.1.1 on 2020-10-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_account_is_profile_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_profile_set',
            field=models.BooleanField(default=False),
        ),
    ]
