# Generated by Django 3.1.1 on 2020-10-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20201006_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_gig',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
