# Generated by Django 3.1.1 on 2020-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_account_first_gig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_gig',
            field=models.BooleanField(default=True),
        ),
    ]
