# Generated by Django 3.1.1 on 2020-10-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20201008_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_create',
            field=models.BooleanField(default=False),
        ),
    ]
