# Generated by Django 3.1.1 on 2020-10-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followed_to',
            field=models.IntegerField(),
        ),
    ]
