# Generated by Django 3.1.1 on 2020-10-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_auto_20201024_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_verified',
            field=models.BooleanField(default=False),
        ),
    ]
