# Generated by Django 3.1.1 on 2020-10-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_account_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_online',
            field=models.BooleanField(default=True),
        ),
    ]
