# Generated by Django 3.1.1 on 2020-10-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_account_user_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_online',
            field=models.BooleanField(default=False),
        ),
    ]
