# Generated by Django 3.1.1 on 2020-10-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_auto_20201030_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
