# Generated by Django 3.1.1 on 2020-10-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_account_last_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_logout',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
