# Generated by Django 3.1.1 on 2020-10-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_auto_20201030_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_logout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
