# Generated by Django 3.1.1 on 2020-10-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_auto_20201030_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
