# Generated by Django 3.1.1 on 2020-10-31 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='message',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='username',
        ),
        migrations.AddField(
            model_name='myorder',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myorder',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
