# Generated by Django 3.1.1 on 2020-10-31 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gig', '0039_auto_20201031_1503'),
        ('Order', '0002_auto_20201031_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='gig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gig.mygig'),
        ),
    ]
