# Generated by Django 3.1.1 on 2020-10-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_myorder_gig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='complete',
        ),
    ]
