# Generated by Django 3.1.1 on 2020-11-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_auto_20201119_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='message',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
