# Generated by Django 3.1.1 on 2020-11-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_auto_20201124_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='payment_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='payment_method',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Cancelled', 'Cancelled')], default='Cash On Delivery', max_length=50),
        ),
    ]
