# Generated by Django 3.1.1 on 2020-11-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0012_auto_20201129_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='payment_complete',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='payment_method',
        ),
    ]
