# Generated by Django 3.1.1 on 2020-11-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_auto_20201129_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Khalti', 'Khalti'), ('E-Sewa', 'E-Sewa')], default='Cash On Delivery', max_length=50),
        ),
    ]
